# Generated by Django 6.0.7 on 2026-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='scholarship_type',
            field=models.CharField(choices=[('academic', 'Academic/Merit'), ('need', 'Need-Based'), ('government', 'Government-Funded'), ('private', 'Private/Corporate'), ('athletic', 'Athletic/Skill-Based')], max_length=20),
        ),
    ]
